[2024-05-24T13:44:09.477+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T13:44:09.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:44:05.439373+00:00 [queued]>
[2024-05-24T13:44:09.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:44:05.439373+00:00 [queued]>
[2024-05-24T13:44:09.499+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T13:44:09.509+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-05-24 13:44:05.439373+00:00
[2024-05-24T13:44:09.515+0000] {standard_task_runner.py:63} INFO - Started process 64 to run task
[2024-05-24T13:44:09.518+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-05-24T13:44:05.439373+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp1u8sm1z5']
[2024-05-24T13:44:09.520+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask s3_upload
[2024-05-24T13:44:09.557+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:44:05.439373+00:00 [running]> on host 8ab8618f57f2
[2024-05-24T13:44:09.624+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='OlivierAssiene' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T13:44:05.439373+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T13:44:05.439373+00:00'
[2024-05-24T13:44:09.625+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T13:44:10.278+0000] {logging_mixin.py:188} INFO - Bucket already exists.
[2024-05-24T13:44:10.278+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T13:44:10.279+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, AWS_BUCKET_NAME, file_path.split('/')[-1])
AttributeError: 'NoneType' object has no attribute 'split'
[2024-05-24T13:44:10.287+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-05-24T13:44:05.439373+00:00, execution_date=20240524T134405, start_date=20240524T134409, end_date=20240524T134410
[2024-05-24T13:44:10.301+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task s3_upload ('NoneType' object has no attribute 'split'; 64)
[2024-05-24T13:44:10.334+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T13:44:10.346+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T13:44:10.348+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
