[2024-05-24T13:48:11.188+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T13:48:11.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:48:07.844680+00:00 [queued]>
[2024-05-24T13:48:11.212+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:48:07.844680+00:00 [queued]>
[2024-05-24T13:48:11.212+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T13:48:11.224+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-05-24 13:48:07.844680+00:00
[2024-05-24T13:48:11.229+0000] {standard_task_runner.py:63} INFO - Started process 80 to run task
[2024-05-24T13:48:11.231+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-05-24T13:48:07.844680+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmp5b_gswwv']
[2024-05-24T13:48:11.234+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask s3_upload
[2024-05-24T13:48:11.276+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:48:07.844680+00:00 [running]> on host 8ab8618f57f2
[2024-05-24T13:48:11.349+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='OlivierAssiene' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T13:48:07.844680+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T13:48:07.844680+00:00'
[2024-05-24T13:48:11.351+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T13:48:11.792+0000] {logging_mixin.py:188} INFO - Bucket already exists.
[2024-05-24T13:48:11.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T13:48:11.793+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, AWS_BUCKET_NAME, file_path.split('/')[-1])
TypeError: upload_to_s3() missing 1 required positional argument: 's3_file_name'
[2024-05-24T13:48:11.803+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-05-24T13:48:07.844680+00:00, execution_date=20240524T134807, start_date=20240524T134811, end_date=20240524T134811
[2024-05-24T13:48:11.815+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task s3_upload (upload_to_s3() missing 1 required positional argument: 's3_file_name'; 80)
[2024-05-24T13:48:11.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T13:48:11.863+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T13:48:11.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
