[2024-05-24T13:12:46.715+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T13:12:46.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:12:36.531336+00:00 [queued]>
[2024-05-24T13:12:46.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:12:36.531336+00:00 [queued]>
[2024-05-24T13:12:46.752+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-24T13:12:46.770+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-05-24 13:12:36.531336+00:00
[2024-05-24T13:12:46.777+0000] {standard_task_runner.py:63} INFO - Started process 52 to run task
[2024-05-24T13:12:46.788+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-05-24T13:12:36.531336+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpmh57d83c']
[2024-05-24T13:12:46.792+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask s3_upload
[2024-05-24T13:12:46.874+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-05-24T13:12:36.531336+00:00 [running]> on host 8ab8618f57f2
[2024-05-24T13:12:46.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='OlivierAssiene' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-05-24T13:12:36.531336+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-24T13:12:36.531336+00:00'
[2024-05-24T13:12:46.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T13:12:47.011+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T13:12:47.012+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 5, in upload_s3_pipeline
    file_path = ti.xcom_pull(task_id='reddit_extraction', key = 'return_value')
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'
[2024-05-24T13:12:47.025+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, run_id=manual__2024-05-24T13:12:36.531336+00:00, execution_date=20240524T131236, start_date=20240524T131246, end_date=20240524T131247
[2024-05-24T13:12:47.041+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task s3_upload (TaskInstance.xcom_pull() got an unexpected keyword argument 'task_id'; 52)
[2024-05-24T13:12:47.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-24T13:12:47.098+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T13:12:47.100+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
